#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Yoha\Qr\Console\Commands\RunTests;
use Symfony\Component\Console\Application;
use Yoha\Qr\Console\Commands\GenerateQrCodeCommand;


$application = new Application('QR Code CLI', '1.0.0');

// Register commands
$application->add(new GenerateQrCodeCommand());
$application->add(new RunTests());

// Run the application
$application->run();
