name: CI-PHP-Unit-test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: gd
          
      - name: Set safe directory
        run: git config --global --add safe.directory /app

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Dump autoload
        run: composer dump-autoload -o

      - name: List src directory with details
        run: ls -lR src

      - name: List all files and directories
        run: ls -lR

      - name: List vendor files
        run: ls -lR vendor

      - name: Debug autoload_psr4.php
        run: cat vendor/composer/autoload_psr4.php

      - name: Check autoload
        run: |
          php -r "require 'vendor/autoload.php'; new Yoha\Qr\Core\FileReader();"

      - name: Run tests
        run: composer test