name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Dump autoload
        run: composer dump-autoload -o

      - name: List files
        run: ls -R

      - name: List src files
        run: ls -R src

      - name: List vendor files
        run: ls -R vendor

      - name: Print environment variables
        run: printenv

      - name: Check autoload
        run: |
          php -r "require 'vendor/autoload.php'; new Yoha\Qr\Core\FileReader();"

      - name: Run tests
        run: vendor/bin/phpunit --configuration phpunit.xml
