name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Dump autoload
        run: composer dump-autoload -o

      - name: List src/Core files
        run: ls -R src/Core

      - name: List vendor files
        run: ls -R vendor

      - name: Debug autoload files
        run: |
          cat vendor/composer/autoload_classmap.php
          cat vendor/composer/autoload_psr4.php

      - name: Check autoload
        run: |
          php -r "require 'vendor/autoload.php'; new Yoha\Qr\Core\FileReader();"

      - name: Run tests
        run: vendor/bin/phpunit --configuration phpunit.xml
