name: PHP Composer

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json', 'composer.lock') }}
          restore-keys: |
            composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pdo, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-progress --no-interaction

      - name: Regenerate autoload files
        run: composer dump-autoload

      - name: Run test suite
        run: |
          composer run-script test
          continue-on-error: true  # Uncomment this if you want the job to continue even if tests fail

      - name: Output PHPUnit result status
        run: echo "Test results have been printed above!"
