name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Regenerate autoload files
      run: composer dump-autoload

    # Running the test suite
    - name: Run test suite
      run: |
        composer run-script test
      continue-on-error: true  # Uncomment this if you want the job to continue even if tests fail

    # Optionally, you can add a step to output the test result status or error message
    - name: Output PHPUnit result status
      run: echo "Test results have been printed above!"
